name: Generate Snake Animation

on:
  # 每天北京时间凌晨3点运行
  schedule:
    - cron: '0 19 * * *'
  # 手动触发
  workflow_dispatch:
  # 推送到main分支时触发
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate Snake Animation

    steps:
      - uses: actions/checkout@v6.0.1

      - name: Generate GitHub Snake Animation
        uses: Platane/snk/svg-only@v3.4.1
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit snake svg
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          mkdir -p output
          cp dist/*.svg output/
          git add output/*.svg
          git commit -m "Update snake animation" || exit 0
          git push